#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Script To Manage Speaker Volume For Archcraft (in Wayland).

# Get Volume
get_volume() {
	volume=$(amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]')
	echo "$volume"
}

